# Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["PNDD.Demo/PNDD.Demo.csproj", "PNDD.Demo/"]
RUN dotnet restore "PNDD.Demo/PNDD.Demo.csproj"
COPY . .
WORKDIR "/src/PNDD.Demo"
RUN dotnet build "PNDD.Demo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PNDD.Demo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PNDD.Demo.dll"]
