version: '3.8'

services:
  pndd-app:
    build:
      context: .
      dockerfile: PNDD.Demo/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - pndd-db

  pndd-db:
    image: postgres:15
    container_name: pndd-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
